services:
  pythonapp:
    build: ./python/
    command: sh - c "sleep 10s ; python3 ./server.py"
    depends_on:
      - mysql

  mysql:
    build: ./mysql/
    restart: always
    environment:
      MYSQL_DATABASE: 'Hospital'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'